services:

  api:
    build: .
    container_name: documind_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      POSTGRES_USER: documind
      POSTGRES_PASSWORD: documind
      POSTGRES_DB: documind
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg18
    container_name: documind_db
    environment:
      POSTGRES_USER: documind
      POSTGRES_PASSWORD: documind
      POSTGRES_DB: documind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: